name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: '0 * * * *'  # Cada hora
  push:
    branches:
      - main  # Asegúrate que es tu rama principal

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: CristianRM05
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg

      - name: Push the generated graph
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generated Pacman contribution graph"
